project:
  type: website

lang: es
date-format: iso

execute:
    freeze: auto

website:
  title: "Investigación Reproducible con Quarto"
  description: "Website del curso Investigación Reproducible con Quarto - XII Congreso Colombiano de Botánica"
  site-url: https://geobota.github.io/xii-ccb-quarto/
  repo-url: https://github.com/geobota/xii-ccb-quarto

  page-navigation: true
  back-to-top-navigation: true
  bread-crumbs: true

  google-analytics:
    tracking-id: "G-QKP4WCQ1Q4"
    anonymize-ip: true

  twitter-card:
    card-style: summary_large_image

  open-graph: true

  navbar:
    # logo: images/logo_reproducible_quarto.png
    right:
      - text: "Inicio"
        href: index.qmd
      - text: "Otros cursos"
        menu:
          - text: "Etnobotánica Cuantitativa en R"
            href: https://geobota.github.io/xii-ccb-etnobotanica/
          - text: "Introducción a la Aerobiología"
            href: https://geobota.github.io/xii-ccb-aerobiologia/
      - text: "XII CCB"
        href: https://congresobotanica.org/
      - text: "ACB"
        href: https://asociacioncolombianadebotanica.com/
      - text: "GEOBOTA"
        href: http://geobota.github.io/
      - icon: facebook
        href: https://www.facebook.com/geobotaudea/
      - icon: instagram
        href: https://www.instagram.com/geobotaudea/
      - icon: github
        href: https://github.com/geobota/xii-ccb-quarto/
  # sidebar:
  #   style: "docked"
  #   logo: images/logo_reproducible_quarto.png

  page-footer:
    center: Made by [@alexespinosaco](https://alexespinosaco.github.io) with {{< fa brands r-project >}} and [![](https://quarto.org/quarto.png){fig-alt="Quarto" width=65px}](https://quarto.org/)

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true